// Importing necessary functions from the '@reduxjs/toolkit' library
import { createSlice, nanoid } from '@reduxjs/toolkit';

// Initial state for the todo slice
const initialState = {
    todos: [{ id: 1, text: "Hello world" }]
};

// Creating a slice of the Redux store using createSlice
export const todoSlice = createSlice({
    // Name of the slice
    name: 'todo',
    // Initial state for the slice
    initialState,
    // Reducers define how the state can be modified
    reducers: {
        // Reducer to add a new todo to the state
        addTodo: (state, action) => {
            // Creating a new todo object with a unique id using nanoid
            const todo = {
                id: nanoid(),
                text: action.payload,
            };
            // Modifying the state by adding the new todo to the 'todos' array
            state.todos.push(todo);
        },
        // Reducer to remove a todo from the state
        removeTodo: (state, action) => {
            // Filtering the 'todos' array to exclude the todo with the specified id
            state.todos = state.todos.filter((todo) => todo.id !== action.payload);
        },
    },
});

// Exporting the action creators from the slice
export const { addTodo, removeTodo } = todoSlice.actions;

// Exporting the reducer function generated by createSlice
export default todoSlice.reducer;
